const FOLDERS = [
{
  id: "01_Introduction",
  title: "01 Introduction",
  banner: "01_Introduction/topic.png",
  videos: [
    { title: "01_Welcome_to_Delta.browser", file: "01_Introduction/01_Welcome_to_Delta.browser.mp4" },
    { title: "02_What_is_the_Internet.browser", file: "01_Introduction/02_What_is_the_Internet.browser.mp4" },
    { title: "03_What_is_Web_Development.browser", file: "01_Introduction/03_What_is_Web_Development.browser.mp4" },        
    { title: "04_What_will_we_learn.browser", file: "01_Introduction/04_What_will_we_learn.browser.mp4" },
  ],
  pdfs: [
  ]
},
{
  id: "02_Prerequisites",
  title: "02 Prerequisites",
  banner: "02_Prerequisites/topic.png",
  videos: [
    { title: "01_Prerequisites.browser", file: "02_Prerequisites/01_Prerequisites.browser.mp4" },
  ],
  pdfs: [
    { title: "02_Installation Guide", file: "02_Prerequisites/02_Installation Guide.pdf" },
  ]
},
{
  id: "03_HTML_Level_1_Part_A",
  title: "03 HTML Level 1 Part A",
  banner: "03_HTML_Level_1_Part_A/topic.png",
  videos: [
    { title: "01_Introduction_to_HTML.browser", file: "03_HTML_Level_1_Part_A/01_Introduction_to_HTML.browser.mp4" },       
    { title: "02_HTML_Elements_Tags.browser", file: "03_HTML_Level_1_Part_A/02_HTML_Elements_Tags.browser.mp4" },
    { title: "03_Hello_World.browser", file: "03_HTML_Level_1_Part_A/03_Hello_World.browser.mp4" },
    { title: "04_Paragraph_Element.browser", file: "03_HTML_Level_1_Part_A/04_Paragraph_Element.browser.mp4" },
    { title: "05_Heading_Elements.browser", file: "03_HTML_Level_1_Part_A/05_Heading_Elements.browser.mp4" },
    { title: "06_Practice_Qs.browser", file: "03_HTML_Level_1_Part_A/06_Practice_Qs.browser.mp4" },
    { title: "07_Boilerplate_Code.browser", file: "03_HTML_Level_1_Part_A/07_Boilerplate_Code.browser.mp4" },
  ],
  pdfs: [
  ]
},
{
  id: "04_HTML_Level_1_Part_B",
  title: "04 HTML Level 1 Part B",
  banner: "04_HTML_Level_1_Part_B/topic.png",
  videos: [
    { title: "01_Lists_in_HTML.browser", file: "04_HTML_Level_1_Part_B/01_Lists_in_HTML.browser.mp4" },
    { title: "02_Attributes_in_HTML.browser", file: "04_HTML_Level_1_Part_B/02_Attributes_in_HTML.browser.mp4" },
    { title: "03_Anchor_Element.browser", file: "04_HTML_Level_1_Part_B/03_Anchor_Element.browser.mp4" },
    { title: "04_Image_Element.browser", file: "04_HTML_Level_1_Part_B/04_Image_Element.browser.mp4" },
    { title: "05_Practice_Qs.browser", file: "04_HTML_Level_1_Part_B/05_Practice_Qs.browser.mp4" },
    { title: "06_More_HTML_Tags.browser", file: "04_HTML_Level_1_Part_B/06_More_HTML_Tags.browser.mp4" },
    { title: "07_Comments_in_HTML.browser", file: "04_HTML_Level_1_Part_B/07_Comments_in_HTML.browser.mp4" },
    { title: "08_Is_HTML_Case_Sensitive.browser", file: "04_HTML_Level_1_Part_B/08_Is_HTML_Case_Sensitive.browser.mp4" },   
    { title: "09_Practice_Qs.browser", file: "04_HTML_Level_1_Part_B/09_Practice_Qs.browser.mp4" },
  ],
  pdfs: [
    { title: "10. HTML (Level 1) Qs", file: "04_HTML_Level_1_Part_B/10. HTML (Level 1) Qs.pdf" },
    { title: "11. HTML Level1 (Ans)", file: "04_HTML_Level_1_Part_B/11. HTML Level1 (Ans).pdf" },
  ]
},
{
  id: "05_HTML_Level_2",
  title: "05 HTML Level 2",
  banner: "05_HTML_Level_2/topic.png",
  videos: [
    { title: "01_Inline_vs_Block.browser", file: "05_HTML_Level_2/01_Inline_vs_Block.browser.mp4" },
    { title: "02_Div_Element.browser", file: "05_HTML_Level_2/02_Div_Element.browser.mp4" },
    { title: "03_Span_Element.browser", file: "05_HTML_Level_2/03_Span_Element.browser.mp4" },
    { title: "04_Hr_Tag.browser", file: "05_HTML_Level_2/04_Hr_Tag.browser.mp4" },
    { title: "05_Sup_Sub_Tags.browser", file: "05_HTML_Level_2/05_Sup_Sub_Tags.browser.mp4" },
    { title: "06_Practice_Qs.browser", file: "05_HTML_Level_2/06_Practice_Qs.browser.mp4" },
    { title: "07_Semantic_Markup.browser", file: "05_HTML_Level_2/07_Semantic_Markup.browser.mp4" },
    { title: "08_Semantic_Tags.browser", file: "05_HTML_Level_2/08_Semantic_Tags.browser.mp4" },
    { title: "09_Practice_Qs.browser", file: "05_HTML_Level_2/09_Practice_Qs.browser.mp4" },
    { title: "10_HTML_Entities.browser", file: "05_HTML_Level_2/10_HTML_Entities.browser.mp4" },
    { title: "11_Practice_Qs.browser", file: "05_HTML_Level_2/11_Practice_Qs.browser.mp4" },
    { title: "12_Emmets.browser", file: "05_HTML_Level_2/12_Emmets.browser.mp4" },
    { title: "13_Further_Understanding_HTML.browser", file: "05_HTML_Level_2/13_Further_Understanding_HTML.browser.mp4" },  
  ],
  pdfs: [
    { title: "14. HTML Level 2 (Qs)", file: "05_HTML_Level_2/14. HTML Level 2 (Qs).pdf" },
    { title: "15. HTML Level 2 (Ans)", file: "05_HTML_Level_2/15. HTML Level 2 (Ans).pdf" },
  ]
},
{
  id: "06_HTML_Level_3",
  title: "06 HTML Level 3",
  banner: "06_HTML_Level_3/topic.png",
  videos: [
    { title: "01_Tables_in_HTML.browser", file: "06_HTML_Level_3/01_Tables_in_HTML.browser.mp4" },
    { title: "02_Semantics_in_Tables.browser", file: "06_HTML_Level_3/02_Semantics_in_Tables.browser.mp4" },
    { title: "03_Colspan_Rowspan_Attributes.browser", file: "06_HTML_Level_3/03_Colspan_Rowspan_Attributes.browser.mp4" },  
    { title: "04_Practice_Qs.browser", file: "06_HTML_Level_3/04_Practice_Qs.browser.mp4" },
    { title: "05_Forms_in_HTML.browser", file: "06_HTML_Level_3/05_Forms_in_HTML.browser.mp4" },
    { title: "06_Input_Form_Element.browser", file: "06_HTML_Level_3/06_Input_Form_Element.browser.mp4" },
    { title: "07_Placeholders_Labels.browser", file: "06_HTML_Level_3/07_Placeholders_Labels.browser.mp4" },
    { title: "08_Button_Element.browser", file: "06_HTML_Level_3/08_Button_Element.browser.mp4" },
    { title: "09_Name_Attribute.browser", file: "06_HTML_Level_3/09_Name_Attribute.browser.mp4" },
    { title: "10_Practice_Qs.browser", file: "06_HTML_Level_3/10_Practice_Qs.browser.mp4" },
    { title: "11_Checkbox_Input_Element.browser", file: "06_HTML_Level_3/11_Checkbox_Input_Element.browser.mp4" },
    { title: "12_Radio_Input_Element.browser", file: "06_HTML_Level_3/12_Radio_Input_Element.browser.mp4" },
    { title: "13_Select_Input_Element.browser", file: "06_HTML_Level_3/13_Select_Input_Element.browser.mp4" },
    { title: "14_Range_Input_Element.browser", file: "06_HTML_Level_3/14_Range_Input_Element.browser.mp4" },
    { title: "15_Text_Area.browser", file: "06_HTML_Level_3/15_Text_Area.browser.mp4" },
    { title: "16_Practice_Qs.browser", file: "06_HTML_Level_3/16_Practice_Qs.browser.mp4" },
  ],
  pdfs: [
    { title: "17. HTML Level 3 (Qs)", file: "06_HTML_Level_3/17. HTML Level 3 (Qs).pdf" },
    { title: "18. HTML Level 3 (Ans)", file: "06_HTML_Level_3/18. HTML Level 3 (Ans).pdf" },
  ]
},
{
  id: "07_CSS_Getting_Started",
  title: "07 CSS Getting Started",
  banner: "07_CSS_Getting_Started/topic.png",
  videos: [
    { title: "01_What_is_CSS.browser", file: "07_CSS_Getting_Started/01_What_is_CSS.browser.mp4" },
    { title: "02_Basic_CSS_Format.browser", file: "07_CSS_Getting_Started/02_Basic_CSS_Format.browser.mp4" },
    { title: "03_Including_CSS.browser", file: "07_CSS_Getting_Started/03_Including_CSS.browser.mp4" },
    { title: "04_Color_Property.browser", file: "07_CSS_Getting_Started/04_Color_Property.browser.mp4" },
    { title: "05_Background_Color_Property.browser", file: "07_CSS_Getting_Started/05_Background_Color_Property.browser.mp4" },
    { title: "06_Practice_Qs.browser", file: "07_CSS_Getting_Started/06_Practice_Qs.browser.mp4" },
    { title: "07_Color_Systems_Name_RGB.browser", file: "07_CSS_Getting_Started/07_Color_Systems_Name_RGB.browser.mp4" },   
    { title: "08_Hex_Codes.browser", file: "07_CSS_Getting_Started/08_Hex_Codes.browser.mp4" },
    { title: "09_Practice_Qs.browser", file: "07_CSS_Getting_Started/09_Practice_Qs.browser.mp4" },
    { title: "10_Text_Align_Property.browser", file: "07_CSS_Getting_Started/10_Text_Align_Property.browser.mp4" },
    { title: "11_Font_Weight_Text_Decoration.browser", file: "07_CSS_Getting_Started/11_Font_Weight_Text_Decoration.browser.mp4" },
    { title: "12_Line_Height_Letter_Spacing.browser", file: "07_CSS_Getting_Started/12_Line_Height_Letter_Spacing.browser.mp4" },
    { title: "13_Units_in_CSS_Pixel.browser", file: "07_CSS_Getting_Started/13_Units_in_CSS_Pixel.browser.mp4" },
    { title: "14_Font_Family.browser", file: "07_CSS_Getting_Started/14_Font_Family.browser.mp4" },
    { title: "15_Practice_Qs.browser", file: "07_CSS_Getting_Started/15_Practice_Qs.browser.mp4" },
  ],
  pdfs: [
    { title: "16. CSS Part1 (Qs)", file: "07_CSS_Getting_Started/16. CSS Part1 (Qs).pdf" },
    { title: "17. CSS Part 1 (Ans)", file: "07_CSS_Getting_Started/17. CSS Part 1 (Ans).pdf" },
  ]
},
{
  id: "08. CSS - Part 2",
  title: "08. CSS - Part 2",
  banner: "08. CSS - Part 2/topic.png",
  videos: [
    { title: "02_How_to_download.browser", file: "08. CSS - Part 2/02_How_to_download.browser.mp4" },
    { title: "03_Universal_Selector.browser", file: "08. CSS - Part 2/03_Universal_Selector.browser.mp4" },
    { title: "04_Element_Selector.browser", file: "08. CSS - Part 2/04_Element_Selector.browser.mp4" },
    { title: "05_Id_Selector.browser", file: "08. CSS - Part 2/05_Id_Selector.browser.mp4" },
    { title: "06_Class_Selector.browser", file: "08. CSS - Part 2/06_Class_Selector.browser.mp4" },
    { title: "07_Practice_Qs.browser", file: "08. CSS - Part 2/07_Practice_Qs.browser.mp4" },
    { title: "08_Descendant_Selector.browser", file: "08. CSS - Part 2/08_Descendant_Selector.browser.mp4" },
    { title: "09_Sibling_Combinator.browser", file: "08. CSS - Part 2/09_Sibling_Combinator.browser.mp4" },
    { title: "10_Child_Combinator.browser", file: "08. CSS - Part 2/10_Child_Combinator.browser.mp4" },
    { title: "11_Attribute_Selector.browser", file: "08. CSS - Part 2/11_Attribute_Selector.browser.mp4" },
    { title: "12_Practice_Qs_2.browser", file: "08. CSS - Part 2/12_Practice_Qs_2.browser.mp4" },
    { title: "13_Pseudo_Class.browser", file: "08. CSS - Part 2/13_Pseudo_Class.browser.mp4" },
    { title: "14_Pseudo_Element.browser", file: "08. CSS - Part 2/14_Pseudo_Element.browser.mp4" },
    { title: "15_Cascading_Specificity.browser", file: "08. CSS - Part 2/15_Cascading_Specificity.browser.mp4" },
    { title: "16_Practice_Qs_3.browser", file: "08. CSS - Part 2/16_Practice_Qs_3.browser.mp4" },
    { title: "17_important_in_CSS.browser", file: "08. CSS - Part 2/17_important_in_CSS.browser.mp4" },
    { title: "18_Inheritance.browser", file: "08. CSS - Part 2/18_Inheritance.browser.mp4" },
  ],
  pdfs: [
    { title: "01. Download Starter HTML", file: "08. CSS - Part 2/01. Download Starter HTML.pdf" },
    { title: "19. CSS Part2 (Qs)", file: "08. CSS - Part 2/19. CSS Part2 (Qs).pdf" },
    { title: "20. CSS Part 2 (Ans)", file: "08. CSS - Part 2/20. CSS Part 2 (Ans).pdf" },
  ]
},
{
  id: "09_CSS_Part_3",
  title: "09 CSS Part 3",
  banner: "09_CSS_Part_3/topic.png",
  videos: [
    { title: "02_Box_Model.browser", file: "09_CSS_Part_3/02_Box_Model.browser.mp4" },
    { title: "03_Height_Width.browser", file: "09_CSS_Part_3/03_Height_Width.browser.mp4" },
    { title: "04_Border.browser", file: "09_CSS_Part_3/04_Border.browser.mp4" },
    { title: "05_Border_Radius.browser", file: "09_CSS_Part_3/05_Border_Radius.browser.mp4" },
    { title: "06_Padding_Property.browser", file: "09_CSS_Part_3/06_Padding_Property.browser.mp4" },
    { title: "07_Margin_Property.browser", file: "09_CSS_Part_3/07_Margin_Property.browser.mp4" },
    { title: "08_Practice_Qs.browser", file: "09_CSS_Part_3/08_Practice_Qs.browser.mp4" },
    { title: "09_Display_Property.browser", file: "09_CSS_Part_3/09_Display_Property.browser.mp4" },
    { title: "11_Inline_Block.browser", file: "09_CSS_Part_3/11_Inline_Block.browser.mp4" },
    { title: "12_Relative_Units_Percentage.browser", file: "09_CSS_Part_3/12_Relative_Units_Percentage.browser.mp4" },      
    { title: "13_Em_Rem_in_Units.browser", file: "09_CSS_Part_3/13_Em_Rem_in_Units.browser.mp4" },
  ],
  pdfs: [
    { title: "01. Download Starter HTML", file: "09_CSS_Part_3/01. Download Starter HTML.pdf" },
    { title: "10 Conclusion (Inline & Block)", file: "09_CSS_Part_3/10 Conclusion (Inline & Block).pdf" },
    { title: "14. CSS Part3 (Qs)", file: "09_CSS_Part_3/14. CSS Part3 (Qs).pdf" },
    { title: "15. CSS Part 3 (Ans)", file: "09_CSS_Part_3/15. CSS Part 3 (Ans).pdf" },
  ]
},
{
  id: "10_CSS_Part_4",
  title: "10 CSS Part 4",
  banner: "10_CSS_Part_4/topic.png",
  videos: [
    { title: "01_Alpha_Opacity.browser", file: "10_CSS_Part_4/01_Alpha_Opacity.browser.mp4" },
    { title: "02_Transitions_in_CSS.browser", file: "10_CSS_Part_4/02_Transitions_in_CSS.browser.mp4" },
    { title: "03_Transform_Rotate.browser", file: "10_CSS_Part_4/03_Transform_Rotate.browser.mp4" },
    { title: "04_Tranform_Scale.browser", file: "10_CSS_Part_4/04_Tranform_Scale.browser.mp4" },
    { title: "05_Transform_Translate.browser", file: "10_CSS_Part_4/05_Transform_Translate.browser.mp4" },
    { title: "06_Transform_Skew.browser", file: "10_CSS_Part_4/06_Transform_Skew.browser.mp4" },
    { title: "07_Box_Shadow.browser", file: "10_CSS_Part_4/07_Box_Shadow.browser.mp4" },
    { title: "08_Background_Image.browser", file: "10_CSS_Part_4/08_Background_Image.browser.mp4" },
    { title: "09_Card_Hover_Effect.browser", file: "10_CSS_Part_4/09_Card_Hover_Effect.browser.mp4" },
    { title: "10_Position_Property.browser", file: "10_CSS_Part_4/10_Position_Property.browser.mp4" },
    { title: "11_Simple_Smiley_Face.browser", file: "10_CSS_Part_4/11_Simple_Smiley_Face.browser.mp4" },
  ],
  pdfs: [
    { title: "12. CSS Part4 (Qs)", file: "10_CSS_Part_4/12. CSS Part4 (Qs).pdf" },
    { title: "13. CSS Part 4 (Ans)", file: "10_CSS_Part_4/13. CSS Part 4 (Ans).pdf" },
  ]
},
{
  id: "11_CSS_Part_5",
  title: "11 CSS Part 5",
  banner: "11_CSS_Part_5/topic.png",
  videos: [
    { title: "01_What_is_Flexbox.browser", file: "11_CSS_Part_5/01_What_is_Flexbox.browser.mp4" },
    { title: "02_Display_Flex.browser", file: "11_CSS_Part_5/02_Display_Flex.browser.mp4" },
    { title: "03_Flex_Direction.browser", file: "11_CSS_Part_5/03_Flex_Direction.browser.mp4" },
    { title: "04_Justify_Content.browser", file: "11_CSS_Part_5/04_Justify_Content.browser.mp4" },
    { title: "05_Flex_Wrap.browser", file: "11_CSS_Part_5/05_Flex_Wrap.browser.mp4" },
    { title: "06_Align_Items.browser", file: "11_CSS_Part_5/06_Align_Items.browser.mp4" },
    { title: "07_Align_Content.browser", file: "11_CSS_Part_5/07_Align_Content.browser.mp4" },
    { title: "08_Align_Self.browser", file: "11_CSS_Part_5/08_Align_Self.browser.mp4" },
    { title: "09_Flex_Sizing.browser", file: "11_CSS_Part_5/09_Flex_Sizing.browser.mp4" },
    { title: "10_Flex_Shorthand.browser", file: "11_CSS_Part_5/10_Flex_Shorthand.browser.mp4" },
  ],
  pdfs: [
    { title: "11. CSS Part5(Qs)", file: "11_CSS_Part_5/11. CSS Part5(Qs).pdf" },
    { title: "12. CSS Part 5 (Ans)", file: "11_CSS_Part_5/12. CSS Part 5 (Ans).pdf" },
    { title: "13. Flowchart-1-2", file: "11_CSS_Part_5/13. Flowchart-1-2.pdf" },
  ]
},
{
  id: "12_CSS_Part_6",
  title: "12 CSS Part 6",
  banner: "12_CSS_Part_6/topic.png",
  videos: [
    { title: "01_What_is_Grid.browser", file: "12_CSS_Part_6/01_What_is_Grid.browser.mp4" },
    { title: "02_Grid_Model.browser", file: "12_CSS_Part_6/02_Grid_Model.browser.mp4" },
    { title: "03_Grid_Template.browser", file: "12_CSS_Part_6/03_Grid_Template.browser.mp4" },
    { title: "04_Grid_Template_repeat.browser", file: "12_CSS_Part_6/04_Grid_Template_repeat.browser.mp4" },
    { title: "05_Grid_Gaps.browser", file: "12_CSS_Part_6/05_Grid_Gaps.browser.mp4" },
    { title: "06_Grid_Columns.browser", file: "12_CSS_Part_6/06_Grid_Columns.browser.mp4" },
    { title: "07_Grid_Rows.browser", file: "12_CSS_Part_6/07_Grid_Rows.browser.mp4" },
    { title: "08_Grid_Properties.browser", file: "12_CSS_Part_6/08_Grid_Properties.browser.mp4" },
    { title: "09_Animation_in_CSS.browser", file: "12_CSS_Part_6/09_Animation_in_CSS.browser.mp4" },
    { title: "10_Animation_Shorthand.browser", file: "12_CSS_Part_6/10_Animation_Shorthand.browser.mp4" },
    { title: "11_in_Animation.browser", file: "12_CSS_Part_6/11_in_Animation.browser.mp4" },
    { title: "12_Media_Queries.browser", file: "12_CSS_Part_6/12_Media_Queries.browser.mp4" },
    { title: "13_Media_Queries_Orientation.browser", file: "12_CSS_Part_6/13_Media_Queries_Orientation.browser.mp4" },      
    { title: "14_Pet_Adoption_Page.browser", file: "12_CSS_Part_6/14_Pet_Adoption_Page.browser.mp4" },
    { title: "16_z_index.browser", file: "12_CSS_Part_6/16_z_index.browser.mp4" },
  ],
  pdfs: [
    { title: "15. Download Starter HTML", file: "12_CSS_Part_6/15. Download Starter HTML.pdf" },
    { title: "17. CSS Part 6 (Qs)", file: "12_CSS_Part_6/17. CSS Part 6 (Qs).pdf" },
    { title: "18. CSS Part 6 (Ans)", file: "12_CSS_Part_6/18. CSS Part 6 (Ans).pdf" },
  ]
},
{
  id: "13_Mini_Project_CSS",
  title: "13 Mini Project CSS",
  banner: "13_Mini_Project_CSS/topic.png",
  videos: [
    { title: "01_Color_Theory.browser", file: "13_Mini_Project_CSS/01_Color_Theory.browser.mp4" },
    { title: "02_Typography.browser", file: "13_Mini_Project_CSS/02_Typography.browser.mp4" },
    { title: "03_Google_Fonts.browser", file: "13_Mini_Project_CSS/03_Google_Fonts.browser.mp4" },
    { title: "04_Icons.browser", file: "13_Mini_Project_CSS/04_Icons.browser.mp4" },
    { title: "06_Introduction.browser", file: "13_Mini_Project_CSS/06_Introduction.browser.mp4" },
    { title: "07_Setting_Style.browser", file: "13_Mini_Project_CSS/07_Setting_Style.browser.mp4" },
    { title: "08_Sidebar_Menu.browser", file: "13_Mini_Project_CSS/08_Sidebar_Menu.browser.mp4" },
    { title: "09_Hover_Changes.browser", file: "13_Mini_Project_CSS/09_Hover_Changes.browser.mp4" },
    { title: "10_Configuring_Checkbox.browser", file: "13_Mini_Project_CSS/10_Configuring_Checkbox.browser.mp4" },
  ],
  pdfs: [
    { title: "05. Download Starter HTML", file: "13_Mini_Project_CSS/05. Download Starter HTML.pdf" },
  ]
},
{
  id: "14_Bootstrap",
  title: "14 Bootstrap",
  banner: "14_Bootstrap/topic.png",
  videos: [
    { title: "01_What_is_Bootstrap.browser", file: "14_Bootstrap/01_What_is_Bootstrap.browser.mp4" },
    { title: "02_Using_Bootstrap.browser", file: "14_Bootstrap/02_Using_Bootstrap.browser.mp4" },
    { title: "03_Container_Layout.browser", file: "14_Bootstrap/03_Container_Layout.browser.mp4" },
    { title: "04_Button_Component.browser", file: "14_Bootstrap/04_Button_Component.browser.mp4" },
    { title: "05_Badge_Component.browser", file: "14_Bootstrap/05_Badge_Component.browser.mp4" },
    { title: "06_Alert_Component.browser", file: "14_Bootstrap/06_Alert_Component.browser.mp4" },
    { title: "07_Button_Group_Component.browser", file: "14_Bootstrap/07_Button_Group_Component.browser.mp4" },
    { title: "08_Navbar_Component.browser", file: "14_Bootstrap/08_Navbar_Component.browser.mp4" },
    { title: "09_Card_Component.browser", file: "14_Bootstrap/09_Card_Component.browser.mp4" },
    { title: "10_Grid_Layout.browser", file: "14_Bootstrap/10_Grid_Layout.browser.mp4" },
    { title: "11_Grid_Vertical_Alignment.browser", file: "14_Bootstrap/11_Grid_Vertical_Alignment.browser.mp4" },
    { title: "12_Form_Controls_in_Bootstrap.browser", file: "14_Bootstrap/12_Form_Controls_in_Bootstrap.browser.mp4" },     
    { title: "13_Select_in_Form.browser", file: "14_Bootstrap/13_Select_in_Form.browser.mp4" },
    { title: "14_Checkbox_Radio_in_Form.browser", file: "14_Bootstrap/14_Checkbox_Radio_in_Form.browser.mp4" },
    { title: "15_Form_Layout.browser", file: "14_Bootstrap/15_Form_Layout.browser.mp4" },
  ],
  pdfs: [
    { title: "16. Bootstrap (Qs)", file: "14_Bootstrap/16. Bootstrap (Qs).pdf" },
    { title: "17. Bootstrap (Ans)", file: "14_Bootstrap/17. Bootstrap (Ans).pdf" },
  ]
},
{
  id: "15_Project_CSS",
  title: "15 Project CSS",
  banner: "15_Project_CSS/topic.png",
  videos: [
    { title: "02_Setting_up.browser", file: "15_Project_CSS/02_Setting_up.browser.mp4" },
    { title: "03_Basics.browser", file: "15_Project_CSS/03_Basics.browser.mp4" },
    { title: "04_Layout.browser", file: "15_Project_CSS/04_Layout.browser.mp4" },
    { title: "05_Sidebar_Nav.browser", file: "15_Project_CSS/05_Sidebar_Nav.browser.mp4" },
    { title: "06_Sidebar_Library.browser", file: "15_Project_CSS/06_Sidebar_Library.browser.mp4" },
    { title: "07_Library_Boxes.browser", file: "15_Project_CSS/07_Library_Boxes.browser.mp4" },
    { title: "08_Sticky_Nav.browser", file: "15_Project_CSS/08_Sticky_Nav.browser.mp4" },
    { title: "09_Cards.browser", file: "15_Project_CSS/09_Cards.browser.mp4" },
    { title: "10_Footer_Line.browser", file: "15_Project_CSS/10_Footer_Line.browser.mp4" },
    { title: "11_Setting_up_Player.browser", file: "15_Project_CSS/11_Setting_up_Player.browser.mp4" },
    { title: "12_Player_Controls.browser", file: "15_Project_CSS/12_Player_Controls.browser.mp4" },
    { title: "13_Playback_Bar.browser", file: "15_Project_CSS/13_Playback_Bar.browser.mp4" },
    { title: "14_Tailwind_CSS.browser", file: "15_Project_CSS/14_Tailwind_CSS.browser.mp4" },
  ],
  pdfs: [
    { title: "01. Download Starter HTML", file: "15_Project_CSS/01. Download Starter HTML.pdf" },
  ]
},
{
  id: "16_JavaScript_Part_1",
  title: "16 JavaScript Part 1",
  banner: "16_JavaScript_Part_1/topic.png",
  videos: [
    { title: "01_Introduction.browser", file: "16_JavaScript_Part_1/01_Introduction.browser.mp4" },
    { title: "02_Using_the_Console.browser", file: "16_JavaScript_Part_1/02_Using_the_Console.browser.mp4" },
    { title: "03_What_is_a_Variable.browser", file: "16_JavaScript_Part_1/03_What_is_a_Variable.browser.mp4" },
    { title: "04_Data_Types_in_JS.browser", file: "16_JavaScript_Part_1/04_Data_Types_in_JS.browser.mp4" },
    { title: "05_Numbers_in_JS.browser", file: "16_JavaScript_Part_1/05_Numbers_in_JS.browser.mp4" },
    { title: "06_Operations_in_JS.browser", file: "16_JavaScript_Part_1/06_Operations_in_JS.browser.mp4" },
    { title: "07_NaN_in_JS.browser", file: "16_JavaScript_Part_1/07_NaN_in_JS.browser.mp4" },
    { title: "08_Operator_Precedence.browser", file: "16_JavaScript_Part_1/08_Operator_Precedence.browser.mp4" },
    { title: "09_let_const_var_Keywords.browser", file: "16_JavaScript_Part_1/09_let_const_var_Keywords.browser.mp4" },
    { title: "10_Practice_Qs.browser", file: "16_JavaScript_Part_1/10_Practice_Qs.browser.mp4" },
    { title: "11_Assignment_Operators.browser", file: "16_JavaScript_Part_1/11_Assignment_Operators.browser.mp4" },
    { title: "12_Unary_Operators.browser", file: "16_JavaScript_Part_1/12_Unary_Operators.browser.mp4" },
    { title: "13_Practice_Qs.browser", file: "16_JavaScript_Part_1/13_Practice_Qs.browser.mp4" },
    { title: "14_Identifier_Rules.browser", file: "16_JavaScript_Part_1/14_Identifier_Rules.browser.mp4" },
    { title: "15_Boolean_in_JS.browser", file: "16_JavaScript_Part_1/15_Boolean_in_JS.browser.mp4" },
    { title: "16_What_is_TypeScript.browser", file: "16_JavaScript_Part_1/16_What_is_TypeScript.browser.mp4" },
    { title: "17_Practice_Qs.browser", file: "16_JavaScript_Part_1/17_Practice_Qs.browser.mp4" },
    { title: "18_String_in_JS.browser", file: "16_JavaScript_Part_1/18_String_in_JS.browser.mp4" },
    { title: "19_String_Indices.browser", file: "16_JavaScript_Part_1/19_String_Indices.browser.mp4" },
    { title: "20_null_undefined_in_JS.browser", file: "16_JavaScript_Part_1/20_null_undefined_in_JS.browser.mp4" },
    { title: "21_Practice_Qs.browser", file: "16_JavaScript_Part_1/21_Practice_Qs.browser.mp4" },
  ],
  pdfs: [
  ]
},
{
  id: "17_JavaScript_Part_2",
  title: "17 JavaScript Part 2",
  banner: "17_JavaScript_Part_2/topic.png",
  videos: [
    { title: "01_console_log.browser", file: "17_JavaScript_Part_2/01_console_log.browser.mp4" },
    { title: "02_Linking_JS_File.browser", file: "17_JavaScript_Part_2/02_Linking_JS_File.browser.mp4" },
    { title: "03_Template_Literals.browser", file: "17_JavaScript_Part_2/03_Template_Literals.browser.mp4" },
    { title: "04_Operators_in_JS.browser", file: "17_JavaScript_Part_2/04_Operators_in_JS.browser.mp4" },
    { title: "05_Comparison_Operators.browser", file: "17_JavaScript_Part_2/05_Comparison_Operators.browser.mp4" },
    { title: "06_Comparison_for_Non_numbers.browser", file: "17_JavaScript_Part_2/06_Comparison_for_Non_numbers.browser.mp4" },
    { title: "07_Conditional_Statements.browser", file: "17_JavaScript_Part_2/07_Conditional_Statements.browser.mp4" },     
    { title: "08_if_Statement.browser", file: "17_JavaScript_Part_2/08_if_Statement.browser.mp4" },
    { title: "09_Practice_Qs.browser", file: "17_JavaScript_Part_2/09_Practice_Qs.browser.mp4" },
    { title: "10_else_if_Statement.browser", file: "17_JavaScript_Part_2/10_else_if_Statement.browser.mp4" },
    { title: "11_else_Statement.browser", file: "17_JavaScript_Part_2/11_else_Statement.browser.mp4" },
    { title: "12_Practice_Qs.browser", file: "17_JavaScript_Part_2/12_Practice_Qs.browser.mp4" },
    { title: "13_Nested_if_else.browser", file: "17_JavaScript_Part_2/13_Nested_if_else.browser.mp4" },
    { title: "14_Logical_Operators.browser", file: "17_JavaScript_Part_2/14_Logical_Operators.browser.mp4" },
    { title: "15_Practice_Qs.browser", file: "17_JavaScript_Part_2/15_Practice_Qs.browser.mp4" },
    { title: "16_truthy_falsy.browser", file: "17_JavaScript_Part_2/16_truthy_falsy.browser.mp4" },
    { title: "17_Switch_Statement.browser", file: "17_JavaScript_Part_2/17_Switch_Statement.browser.mp4" },
    { title: "18_Practice_Qs.browser", file: "17_JavaScript_Part_2/18_Practice_Qs.browser.mp4" },
    { title: "19_Alerts_Prompts.browser", file: "17_JavaScript_Part_2/19_Alerts_Prompts.browser.mp4" },
  ],
  pdfs: [
    { title: "20. JS Part2 (Qs)", file: "17_JavaScript_Part_2/20. JS Part2 (Qs).pdf" },
    { title: "21. JS Part 2 (Ans)", file: "17_JavaScript_Part_2/21. JS Part 2 (Ans).pdf" },
  ]
},
{
  id: "18_JavaScript_Part_3",
  title: "18 JavaScript Part 3",
  banner: "18_JavaScript_Part_3/topic.png",
  videos: [
    { title: "01_String_Methods.browser", file: "18_JavaScript_Part_3/01_String_Methods.browser.mp4" },
    { title: "02_Trim_Method.browser", file: "18_JavaScript_Part_3/02_Trim_Method.browser.mp4" },
    { title: "03_Strings_are_Immutable_in_JS.browser", file: "18_JavaScript_Part_3/03_Strings_are_Immutable_in_JS.browser.mp4" },
    { title: "04_ToUpperCase_and_ToLowerCase.browser", file: "18_JavaScript_Part_3/04_ToUpperCase_and_ToLowerCase.browser.mp4" },
    { title: "05_Methods_with_Arguments_indexOf.browser", file: "18_JavaScript_Part_3/05_Methods_with_Arguments_indexOf.browser.mp4" },
    { title: "06_Method_Chaining.browser", file: "18_JavaScript_Part_3/06_Method_Chaining.browser.mp4" },
    { title: "07_Slice_Method.browser", file: "18_JavaScript_Part_3/07_Slice_Method.browser.mp4" },
    { title: "08_Replace_Repeat_Method.browser", file: "18_JavaScript_Part_3/08_Replace_Repeat_Method.browser.mp4" },
    { title: "09_Practice_Qs.browser", file: "18_JavaScript_Part_3/09_Practice_Qs.browser.mp4" },
    { title: "10_Array_Data_Structure.browser", file: "18_JavaScript_Part_3/10_Array_Data_Structure.browser.mp4" },
    { title: "11_Visualizing_Arrays.browser", file: "18_JavaScript_Part_3/11_Visualizing_Arrays.browser.mp4" },
    { title: "12_Creating_Arrays.browser", file: "18_JavaScript_Part_3/12_Creating_Arrays.browser.mp4" },
    { title: "13_Arrays_are_Mutable.browser", file: "18_JavaScript_Part_3/13_Arrays_are_Mutable.browser.mp4" },
    { title: "14_Array_Methods.browser", file: "18_JavaScript_Part_3/14_Array_Methods.browser.mp4" },
    { title: "15_Practice_Qs.browser", file: "18_JavaScript_Part_3/15_Practice_Qs.browser.mp4" },
    { title: "16_indexOf_includes_Method.browser", file: "18_JavaScript_Part_3/16_indexOf_includes_Method.browser.mp4" },   
    { title: "17_Concatenation_Reverse.browser", file: "18_JavaScript_Part_3/17_Concatenation_Reverse.browser.mp4" },       
    { title: "18_Slice_in_Arrays.browser", file: "18_JavaScript_Part_3/18_Slice_in_Arrays.browser.mp4" },
    { title: "19_Splice_in_Arrays.browser", file: "18_JavaScript_Part_3/19_Splice_in_Arrays.browser.mp4" },
    { title: "20_Sort_in_Arrays.browser", file: "18_JavaScript_Part_3/20_Sort_in_Arrays.browser.mp4" },
    { title: "21_Practice_Qs.browser", file: "18_JavaScript_Part_3/21_Practice_Qs.browser.mp4" },
    { title: "22_Arrays_References.browser", file: "18_JavaScript_Part_3/22_Arrays_References.browser.mp4" },
    { title: "23_Constant_Arrays.browser", file: "18_JavaScript_Part_3/23_Constant_Arrays.browser.mp4" },
    { title: "24_Nested_Arrays.browser", file: "18_JavaScript_Part_3/24_Nested_Arrays.browser.mp4" },
    { title: "25_Practice_Qs.browser", file: "18_JavaScript_Part_3/25_Practice_Qs.browser.mp4" },
  ],
  pdfs: [
    { title: "26. JS Part3 (Qs)", file: "18_JavaScript_Part_3/26. JS Part3 (Qs).pdf" },
    { title: "27. JS Part 3 (Ans)", file: "18_JavaScript_Part_3/27. JS Part 3 (Ans).pdf" },
  ]
},
{
  id: "19_JavaScript_Part_4",
  title: "19 JavaScript Part 4",
  banner: "19_JavaScript_Part_4/topic.png",
  videos: [
    { title: "01. for Loops", file: "19_JavaScript_Part_4/01. for Loops.mp4" },
    { title: "02. Dry Run", file: "19_JavaScript_Part_4/02. Dry Run.mp4" },
    { title: "03. Print Odd Numbers", file: "19_JavaScript_Part_4/03. Print Odd Numbers.mp4" },
    { title: "04. Print Even Numbers", file: "19_JavaScript_Part_4/04. Print Even Numbers.mp4" },
    { title: "05. Infinite Loops", file: "19_JavaScript_Part_4/05. Infinite Loops.mp4" },
    { title: "06. Print Multiplication Table", file: "19_JavaScript_Part_4/06. Print Multiplication Table.mp4" },
    { title: "07. Nested for Loop", file: "19_JavaScript_Part_4/07. Nested for Loop.mp4" },
    { title: "08. while Loops", file: "19_JavaScript_Part_4/08. while Loops.mp4" },
    { title: "09. Favorite Movie", file: "19_JavaScript_Part_4/09. Favorite Movie.mp4" },
    { title: "10. break Keyword", file: "19_JavaScript_Part_4/10. break Keyword.mp4" },
    { title: "11. Loops with Arrays", file: "19_JavaScript_Part_4/11. Loops with Arrays.mp4" },
    { title: "12. Loops with Nested Arrays", file: "19_JavaScript_Part_4/12. Loops with Nested Arrays.mp4" },
    { title: "13. for-of Loops", file: "19_JavaScript_Part_4/13. for-of Loops.mp4" },
    { title: "14. Nested for-of Loop", file: "19_JavaScript_Part_4/14. Nested for-of Loop.mp4" },
    { title: "15. Todo App (only JS)", file: "19_JavaScript_Part_4/15. Todo App (only JS).mp4" },
  ],
  pdfs: [
    { title: "16. JS Part 4 (Qs)", file: "19_JavaScript_Part_4/16. JS Part 4 (Qs).pdf" },
    { title: "17. JS Part 4 (Ans)", file: "19_JavaScript_Part_4/17. JS Part 4 (Ans).pdf" },
  ]
},
{
  id: "20_JavaScript_Part_5",
  title: "20 JavaScript Part 5",
  banner: "20_JavaScript_Part_5/topic.png",
  videos: [
    { title: "01. Object Literals", file: "20_JavaScript_Part_5/01. Object Literals.mp4" },
    { title: "02. Creating Object Literals", file: "20_JavaScript_Part_5/02. Creating Object Literals.mp4" },
    { title: "03. Creating a Post", file: "20_JavaScript_Part_5/03. Creating a Post.mp4" },
    { title: "04. Get Values", file: "20_JavaScript_Part_5/04. Get Values.mp4" },
    { title: "05. Conversion in Get Values", file: "20_JavaScript_Part_5/05. Conversion in Get Values.mp4" },
    { title: "06. Add _ Update Values", file: "20_JavaScript_Part_5/06. Add _ Update Values.mp4" },
    { title: "07. Nested Objects", file: "20_JavaScript_Part_5/07. Nested Objects.mp4" },
    { title: "08. Array of Objects", file: "20_JavaScript_Part_5/08. Array of Objects.mp4" },
    { title: "09. Math Object", file: "20_JavaScript_Part_5/09. Math Object.mp4" },
    { title: "10. Random Integers", file: "20_JavaScript_Part_5/10. Random Integers.mp4" },
    { title: "11. Practice Qs", file: "20_JavaScript_Part_5/11. Practice Qs.mp4" },
    { title: "12. Guessing Game", file: "20_JavaScript_Part_5/12. Guessing Game.mp4" },
  ],
  pdfs: [
    { title: "13. JS Part 5 (Qs)", file: "20_JavaScript_Part_5/13. JS Part 5 (Qs).pdf" },
    { title: "14. JS Part 5 (Ans)", file: "20_JavaScript_Part_5/14. JS Part 5 (Ans).pdf" },
  ]
},
{
  id: "21_JavaScript_Part_6",
  title: "21 JavaScript Part 6",
  banner: "21_JavaScript_Part_6/topic.png",
  videos: [
    { title: "01_What_are_functions.browser", file: "21_JavaScript_Part_6/01_What_are_functions.browser.mp4" },
    { title: "02_Practice_Qs1.browser", file: "21_JavaScript_Part_6/02_Practice_Qs1.browser.mp4" },
    { title: "03_Practice_Qs_2.browser", file: "21_JavaScript_Part_6/03_Practice_Qs_2.browser.mp4" },
    { title: "04_Functions_with_Arguments.browser", file: "21_JavaScript_Part_6/04_Functions_with_Arguments.browser.mp4" },
    { title: "05_Practice_Qs_3.browser", file: "21_JavaScript_Part_6/05_Practice_Qs_3.browser.mp4" },
    { title: "06_Practice_Qs_4.browser", file: "21_JavaScript_Part_6/06_Practice_Qs_4.browser.mp4" },
    { title: "07_return_Keyword.browser", file: "21_JavaScript_Part_6/07_return_Keyword.browser.mp4" },
    { title: "08_Practice_Qs_5.browser", file: "21_JavaScript_Part_6/08_Practice_Qs_5.browser.mp4" },
    { title: "09_Practice_Qs_6.browser", file: "21_JavaScript_Part_6/09_Practice_Qs_6.browser.mp4" },
    { title: "10_What_is_Scope.browser", file: "21_JavaScript_Part_6/10_What_is_Scope.browser.mp4" },
    { title: "11_Block_Scope.browser", file: "21_JavaScript_Part_6/11_Block_Scope.browser.mp4" },
    { title: "12_Lexical_Scope.browser", file: "21_JavaScript_Part_6/12_Lexical_Scope.browser.mp4" },
    { title: "13_Practice_Qs_7.browser", file: "21_JavaScript_Part_6/13_Practice_Qs_7.browser.mp4" },
    { title: "14_Functions_Expressions.browser", file: "21_JavaScript_Part_6/14_Functions_Expressions.browser.mp4" },
    { title: "15_Higher_Order_Functions.browser", file: "21_JavaScript_Part_6/15_Higher_Order_Functions.browser.mp4" },
    { title: "16_Higher_Order_Functions_Returns.browser", file: "21_JavaScript_Part_6/16_Higher_Order_Functions_Returns.browser.mp4" },
    { title: "17_Methods.browser", file: "21_JavaScript_Part_6/17_Methods.browser.mp4" }
  ],
  pdfs: [
    { title: "18. JS Part 6 (Qs)", file: "20_JavaScript_Part_5/18. JS Part 6 (Qs).pdf" },
    { title: "19. JS Part 6 (Ans)", file: "20_JavaScript_Part_5/19. JS Part 6 (Ans)pdf" },
  ]
},

{
  id: "22_JavaScript_Part_7",
  title: "22 JavaScript Part 7",
  banner: "22_JavaScript_Part_7/topic.png",
  videos: [
    { title: "01. 'this' in JavaScript", file: "22_JavaScript_Part_7/01. 'this' in JavaScript.mp4" },
    { title: "02. Try & Catch", file: "22_JavaScript_Part_7/02. Try & Catch.mp4" },
    { title: "03. Arrow Functions", file: "22_JavaScript_Part_7/03. Arrow Functions.mp4" },
    { title: "04. Implicit Return in Arrow Functions", file: "22_JavaScript_Part_7/04. Implicit Return in Arrow Functions.mp4" },
    { title: "05. Set TimeOut Function", file: "22_JavaScript_Part_7/05. Set TimeOut Function.mp4" },
    { title: "06. Set Interval Function", file: "22_JavaScript_Part_7/06. Set Interval Function.mp4" },
    { title: "07. this with Arrow Functions", file: "22_JavaScript_Part_7/07. this with Arrow Functions.mp4" },
    { title: "08. Practice Qs", file: "22_JavaScript_Part_7/08. Practice Qs.mp4" },
  ],
  pdfs: [
    { title: "09. JS Part 7 (Qs)", file: "22_JavaScript_Part_7/09. JS Part 7 (Qs).pdf" },
    { title: "10. JS Part 7 (Ans)", file: "22_JavaScript_Part_7/10. JS Part 7 (Ans).pdf" },
  ]
},
{
  id: "23_JavaScript_Part_8",
  title: "23 JavaScript Part 8",
  banner: "23_JavaScript_Part_8/topic.png",
  videos: [
    { title: "01. Array Methods", file: "23_JavaScript_Part_8/01. Array Methods.mp4" },
    { title: "02. Map & Filter", file: "23_JavaScript_Part_8/02. Map & Filter.mp4" },
    { title: "03. Every & Sum", file: "23_JavaScript_Part_8/03. Every & Sum.mp4" },
    { title: "04. Reduce Method", file: "23_JavaScript_Part_8/04. Reduce Method.mp4" },
    { title: "05. Maximum in Array", file: "23_JavaScript_Part_8/05. Maximum in Array.mp4" },
    { title: "06. Practice Qs", file: "23_JavaScript_Part_8/06. Practice Qs.mp4" },
    { title: "07. Default Parameters", file: "23_JavaScript_Part_8/07. Default Parameters.mp4" },
    { title: "08. Spread", file: "23_JavaScript_Part_8/08. Spread.mp4" },
    { title: "09. Spread (Array Literals)", file: "23_JavaScript_Part_8/09. Spread (Array Literals).mp4" },
    { title: "10. Spread (Object Literals)", file: "23_JavaScript_Part_8/10. Spread (Object Literals).mp4" },
    { title: "11. Rest", file: "23_JavaScript_Part_8/11. Rest.mp4" },
    { title: "12. Destructuring", file: "23_JavaScript_Part_8/12. Destructuring.mp4" },
    { title: "13. Destructuring (Objects)", file: "23_JavaScript_Part_8/13. Destructuring (Objects).mp4" },
  ],
  pdfs: [
    { title: "14. JS Part 8 (Qs)", file: "23_JavaScript_Part_8/14. JS Part 8 (Qs).pdf" },
    { title: "15. JS Part 8 (Ans)", file: "23_JavaScript_Part_8/15. JS Part 8 (Ans).pdf" },
  ]
},
{
  id: "25_JavaScript_Part_10",
  title: "25 JavaScript Part 10",
  banner: "25_JavaScript_Part_10/topic.png",
  videos: [
    { title: "01. DOM Events", file: "25_JavaScript_Part_10/01. DOM Events.mp4" },
    { title: "02. Mouse_ Pointer Events", file: "25_JavaScript_Part_10/02. Mouse_ Pointer Events.mp4" },
    { title: "03. Event Listeners", file: "25_JavaScript_Part_10/03. Event Listeners.mp4" },
    { title: "04. Activity", file: "25_JavaScript_Part_10/04. Activity.mp4" },
    { title: "05. Event Listeners for Elements", file: "25_JavaScript_Part_10/05. Event Listeners for Elements.mp4" },      
    { title: "06. this in Event Listeners", file: "25_JavaScript_Part_10/06. this in Event Listeners.mp4" },
    { title: "07. Keyboard Events", file: "25_JavaScript_Part_10/07. Keyboard Events.mp4" },
    { title: "08. Form Events", file: "25_JavaScript_Part_10/08. Form Events.mp4" },
    { title: "09. Extracting Form Data", file: "25_JavaScript_Part_10/09. Extracting Form Data.mp4" },
    { title: "10. More Events", file: "25_JavaScript_Part_10/10. More Events.mp4" },
  ],
  pdfs: [
    { title: "11. JS Part 10 (Qs)", file: "25_JavaScript_Part_10/11. JS Part 10 (Qs).pdf" },
  ]
},

]
